/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ParameterBreakdown = IDL.Record({
  'maxPoints' : IDL.Nat,
  'pointsScored' : IDL.Nat,
  'parameter' : IDL.Text,
  'userAnswer' : IDL.Text,
});
export const ScoreResult = IDL.Record({
  'freeTextModifier' : IDL.Int,
  'band' : IDL.Text,
  'breakdown' : IDL.Vec(ParameterBreakdown),
  'totalScore' : IDL.Int,
  'baseScore' : IDL.Nat,
  'assessmentId' : IDL.Text,
});
export const BrigadeReport = IDL.Variant({
  'Available' : IDL.Null,
  'NotAvailable' : IDL.Null,
  'Pending' : IDL.Null,
});
export const SurveyorStatus = IDL.Variant({
  'Favourable' : IDL.Null,
  'Unfavourable' : IDL.Null,
  'NotAppointed' : IDL.Null,
  'Pending' : IDL.Null,
});
export const FireCause = IDL.Variant({
  'NaturalCalamity' : IDL.Null,
  'GasExplosion' : IDL.Null,
  'Arson' : IDL.Null,
  'Electrical' : IDL.Null,
  'Other' : IDL.Null,
  'Accidental' : IDL.Null,
});
export const PolicyStatus = IDL.Variant({
  'Inactive' : IDL.Null,
  'Active' : IDL.Null,
  'Unsure' : IDL.Null,
});
export const DocumentStatus = IDL.Variant({
  'Complete' : IDL.Null,
  'Partial' : IDL.Null,
  'Incomplete' : IDL.Null,
});
export const ReportingDelay = IDL.Variant({
  'Within3Days' : IDL.Null,
  'SameDay' : IDL.Null,
  'Days4To7' : IDL.Null,
  'Days8To15' : IDL.Null,
  'Over15Days' : IDL.Null,
});
export const AssessmentInput = IDL.Record({
  'brigadeReport' : BrigadeReport,
  'surveyorStatus' : SurveyorStatus,
  'fireCause' : FireCause,
  'fireCauseText' : IDL.Text,
  'policyStatus' : PolicyStatus,
  'documentStatus' : DocumentStatus,
  'reportingDelayText' : IDL.Text,
  'policyStatusText' : IDL.Text,
  'additionalContext' : IDL.Text,
  'brigadeReportText' : IDL.Text,
  'documentStatusText' : IDL.Text,
  'surveyorStatusText' : IDL.Text,
  'reportingDelay' : ReportingDelay,
});
export const Assessment = IDL.Record({
  'id' : IDL.Text,
  'result' : ScoreResult,
  'owner' : IDL.Principal,
  'createdAt' : IDL.Int,
  'input' : AssessmentInput,
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAssessment' : IDL.Func([IDL.Text], [IDL.Opt(Assessment)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAssessments' : IDL.Func([], [IDL.Vec(Assessment)], ['query']),
  'submitAssessment' : IDL.Func([AssessmentInput], [ScoreResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ParameterBreakdown = IDL.Record({
    'maxPoints' : IDL.Nat,
    'pointsScored' : IDL.Nat,
    'parameter' : IDL.Text,
    'userAnswer' : IDL.Text,
  });
  const ScoreResult = IDL.Record({
    'freeTextModifier' : IDL.Int,
    'band' : IDL.Text,
    'breakdown' : IDL.Vec(ParameterBreakdown),
    'totalScore' : IDL.Int,
    'baseScore' : IDL.Nat,
    'assessmentId' : IDL.Text,
  });
  const BrigadeReport = IDL.Variant({
    'Available' : IDL.Null,
    'NotAvailable' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const SurveyorStatus = IDL.Variant({
    'Favourable' : IDL.Null,
    'Unfavourable' : IDL.Null,
    'NotAppointed' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const FireCause = IDL.Variant({
    'NaturalCalamity' : IDL.Null,
    'GasExplosion' : IDL.Null,
    'Arson' : IDL.Null,
    'Electrical' : IDL.Null,
    'Other' : IDL.Null,
    'Accidental' : IDL.Null,
  });
  const PolicyStatus = IDL.Variant({
    'Inactive' : IDL.Null,
    'Active' : IDL.Null,
    'Unsure' : IDL.Null,
  });
  const DocumentStatus = IDL.Variant({
    'Complete' : IDL.Null,
    'Partial' : IDL.Null,
    'Incomplete' : IDL.Null,
  });
  const ReportingDelay = IDL.Variant({
    'Within3Days' : IDL.Null,
    'SameDay' : IDL.Null,
    'Days4To7' : IDL.Null,
    'Days8To15' : IDL.Null,
    'Over15Days' : IDL.Null,
  });
  const AssessmentInput = IDL.Record({
    'brigadeReport' : BrigadeReport,
    'surveyorStatus' : SurveyorStatus,
    'fireCause' : FireCause,
    'fireCauseText' : IDL.Text,
    'policyStatus' : PolicyStatus,
    'documentStatus' : DocumentStatus,
    'reportingDelayText' : IDL.Text,
    'policyStatusText' : IDL.Text,
    'additionalContext' : IDL.Text,
    'brigadeReportText' : IDL.Text,
    'documentStatusText' : IDL.Text,
    'surveyorStatusText' : IDL.Text,
    'reportingDelay' : ReportingDelay,
  });
  const Assessment = IDL.Record({
    'id' : IDL.Text,
    'result' : ScoreResult,
    'owner' : IDL.Principal,
    'createdAt' : IDL.Int,
    'input' : AssessmentInput,
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAssessment' : IDL.Func([IDL.Text], [IDL.Opt(Assessment)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAssessments' : IDL.Func([], [IDL.Vec(Assessment)], ['query']),
    'submitAssessment' : IDL.Func([AssessmentInput], [ScoreResult], []),
  });
};

export const init = ({ IDL }) => { return []; };