/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Assessment {
  'id' : string,
  'result' : ScoreResult,
  'owner' : Principal,
  'createdAt' : bigint,
  'input' : AssessmentInput,
}
export interface AssessmentInput {
  'brigadeReport' : BrigadeReport,
  'surveyorStatus' : SurveyorStatus,
  'fireCause' : FireCause,
  'fireCauseText' : string,
  'policyStatus' : PolicyStatus,
  'documentStatus' : DocumentStatus,
  'reportingDelayText' : string,
  'policyStatusText' : string,
  'additionalContext' : string,
  'brigadeReportText' : string,
  'documentStatusText' : string,
  'surveyorStatusText' : string,
  'reportingDelay' : ReportingDelay,
}
export type BrigadeReport = { 'Available' : null } |
  { 'NotAvailable' : null } |
  { 'Pending' : null };
export type DocumentStatus = { 'Complete' : null } |
  { 'Partial' : null } |
  { 'Incomplete' : null };
export type FireCause = { 'NaturalCalamity' : null } |
  { 'GasExplosion' : null } |
  { 'Arson' : null } |
  { 'Electrical' : null } |
  { 'Other' : null } |
  { 'Accidental' : null };
export interface ParameterBreakdown {
  'maxPoints' : bigint,
  'pointsScored' : bigint,
  'parameter' : string,
  'userAnswer' : string,
}
export type PolicyStatus = { 'Inactive' : null } |
  { 'Active' : null } |
  { 'Unsure' : null };
export type ReportingDelay = { 'Within3Days' : null } |
  { 'SameDay' : null } |
  { 'Days4To7' : null } |
  { 'Days8To15' : null } |
  { 'Over15Days' : null };
export interface ScoreResult {
  'freeTextModifier' : bigint,
  'band' : string,
  'breakdown' : Array<ParameterBreakdown>,
  'totalScore' : bigint,
  'baseScore' : bigint,
  'assessmentId' : string,
}
export type SurveyorStatus = { 'Favourable' : null } |
  { 'Unfavourable' : null } |
  { 'NotAppointed' : null } |
  { 'Pending' : null };
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAssessment' : ActorMethod<[string], [] | [Assessment]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAssessments' : ActorMethod<[], Array<Assessment>>,
  'submitAssessment' : ActorMethod<[AssessmentInput], ScoreResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];