/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Assessment {
    id: string;
    result: ScoreResult;
    owner: Principal;
    createdAt: bigint;
    input: AssessmentInput;
}
export interface ScoreResult {
    freeTextModifier: bigint;
    band: string;
    breakdown: Array<ParameterBreakdown>;
    totalScore: bigint;
    baseScore: bigint;
    assessmentId: string;
}
export interface AssessmentInput {
    brigadeReport: BrigadeReport;
    surveyorStatus: SurveyorStatus;
    fireCause: FireCause;
    fireCauseText: string;
    policyStatus: PolicyStatus;
    documentStatus: DocumentStatus;
    reportingDelayText: string;
    policyStatusText: string;
    additionalContext: string;
    brigadeReportText: string;
    documentStatusText: string;
    surveyorStatusText: string;
    reportingDelay: ReportingDelay;
}
export interface ParameterBreakdown {
    maxPoints: bigint;
    pointsScored: bigint;
    parameter: string;
    userAnswer: string;
}
export enum BrigadeReport {
    Available = "Available",
    NotAvailable = "NotAvailable",
    Pending = "Pending"
}
export enum DocumentStatus {
    Complete = "Complete",
    Partial_ = "Partial",
    Incomplete = "Incomplete"
}
export enum FireCause {
    NaturalCalamity = "NaturalCalamity",
    GasExplosion = "GasExplosion",
    Arson = "Arson",
    Electrical = "Electrical",
    Other = "Other",
    Accidental = "Accidental"
}
export enum PolicyStatus {
    Inactive = "Inactive",
    Active = "Active",
    Unsure = "Unsure"
}
export enum ReportingDelay {
    Within3Days = "Within3Days",
    SameDay = "SameDay",
    Days4To7 = "Days4To7",
    Days8To15 = "Days8To15",
    Over15Days = "Over15Days"
}
export enum SurveyorStatus {
    Favourable = "Favourable",
    Unfavourable = "Unfavourable",
    NotAppointed = "NotAppointed",
    Pending = "Pending"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getAssessment(id: string): Promise<Assessment | null>;
    getCallerUserRole(): Promise<UserRole>;
    isCallerAdmin(): Promise<boolean>;
    listAssessments(): Promise<Array<Assessment>>;
    submitAssessment(input: AssessmentInput): Promise<ScoreResult>;
}
import type { Assessment as _Assessment, AssessmentInput as _AssessmentInput, BrigadeReport as _BrigadeReport, DocumentStatus as _DocumentStatus, FireCause as _FireCause, PolicyStatus as _PolicyStatus, ReportingDelay as _ReportingDelay, ScoreResult as _ScoreResult, SurveyorStatus as _SurveyorStatus, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAssessment(arg0: string): Promise<Assessment | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAssessment(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAssessment(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listAssessments(): Promise<Array<Assessment>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAssessments();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAssessments();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitAssessment(arg0: AssessmentInput): Promise<ScoreResult> {
        if (this.processError) {
            try {
                const result = await this.actor.submitAssessment(to_candid_AssessmentInput_n23(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitAssessment(to_candid_AssessmentInput_n23(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_AssessmentInput_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AssessmentInput): AssessmentInput {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Assessment_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Assessment): Assessment {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_BrigadeReport_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BrigadeReport): BrigadeReport {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_DocumentStatus_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DocumentStatus): DocumentStatus {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_FireCause_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FireCause): FireCause {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_PolicyStatus_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PolicyStatus): PolicyStatus {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_ReportingDelay_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReportingDelay): ReportingDelay {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_SurveyorStatus_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SurveyorStatus): SurveyorStatus {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Assessment]): Assessment | null {
    return value.length === 0 ? null : from_candid_Assessment_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    result: _ScoreResult;
    owner: Principal;
    createdAt: bigint;
    input: _AssessmentInput;
}): {
    id: string;
    result: ScoreResult;
    owner: Principal;
    createdAt: bigint;
    input: AssessmentInput;
} {
    return {
        id: value.id,
        result: value.result,
        owner: value.owner,
        createdAt: value.createdAt,
        input: from_candid_AssessmentInput_n6(_uploadFile, _downloadFile, value.input)
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    brigadeReport: _BrigadeReport;
    surveyorStatus: _SurveyorStatus;
    fireCause: _FireCause;
    fireCauseText: string;
    policyStatus: _PolicyStatus;
    documentStatus: _DocumentStatus;
    reportingDelayText: string;
    policyStatusText: string;
    additionalContext: string;
    brigadeReportText: string;
    documentStatusText: string;
    surveyorStatusText: string;
    reportingDelay: _ReportingDelay;
}): {
    brigadeReport: BrigadeReport;
    surveyorStatus: SurveyorStatus;
    fireCause: FireCause;
    fireCauseText: string;
    policyStatus: PolicyStatus;
    documentStatus: DocumentStatus;
    reportingDelayText: string;
    policyStatusText: string;
    additionalContext: string;
    brigadeReportText: string;
    documentStatusText: string;
    surveyorStatusText: string;
    reportingDelay: ReportingDelay;
} {
    return {
        brigadeReport: from_candid_BrigadeReport_n8(_uploadFile, _downloadFile, value.brigadeReport),
        surveyorStatus: from_candid_SurveyorStatus_n10(_uploadFile, _downloadFile, value.surveyorStatus),
        fireCause: from_candid_FireCause_n12(_uploadFile, _downloadFile, value.fireCause),
        fireCauseText: value.fireCauseText,
        policyStatus: from_candid_PolicyStatus_n14(_uploadFile, _downloadFile, value.policyStatus),
        documentStatus: from_candid_DocumentStatus_n16(_uploadFile, _downloadFile, value.documentStatus),
        reportingDelayText: value.reportingDelayText,
        policyStatusText: value.policyStatusText,
        additionalContext: value.additionalContext,
        brigadeReportText: value.brigadeReportText,
        documentStatusText: value.documentStatusText,
        surveyorStatusText: value.surveyorStatusText,
        reportingDelay: from_candid_ReportingDelay_n18(_uploadFile, _downloadFile, value.reportingDelay)
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Favourable: null;
} | {
    Unfavourable: null;
} | {
    NotAppointed: null;
} | {
    Pending: null;
}): SurveyorStatus {
    return "Favourable" in value ? SurveyorStatus.Favourable : "Unfavourable" in value ? SurveyorStatus.Unfavourable : "NotAppointed" in value ? SurveyorStatus.NotAppointed : "Pending" in value ? SurveyorStatus.Pending : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    NaturalCalamity: null;
} | {
    GasExplosion: null;
} | {
    Arson: null;
} | {
    Electrical: null;
} | {
    Other: null;
} | {
    Accidental: null;
}): FireCause {
    return "NaturalCalamity" in value ? FireCause.NaturalCalamity : "GasExplosion" in value ? FireCause.GasExplosion : "Arson" in value ? FireCause.Arson : "Electrical" in value ? FireCause.Electrical : "Other" in value ? FireCause.Other : "Accidental" in value ? FireCause.Accidental : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Inactive: null;
} | {
    Active: null;
} | {
    Unsure: null;
}): PolicyStatus {
    return "Inactive" in value ? PolicyStatus.Inactive : "Active" in value ? PolicyStatus.Active : "Unsure" in value ? PolicyStatus.Unsure : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Complete: null;
} | {
    Partial: null;
} | {
    Incomplete: null;
}): DocumentStatus {
    return "Complete" in value ? DocumentStatus.Complete : "Partial" in value ? DocumentStatus.Partial : "Incomplete" in value ? DocumentStatus.Incomplete : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Within3Days: null;
} | {
    SameDay: null;
} | {
    Days4To7: null;
} | {
    Days8To15: null;
} | {
    Over15Days: null;
}): ReportingDelay {
    return "Within3Days" in value ? ReportingDelay.Within3Days : "SameDay" in value ? ReportingDelay.SameDay : "Days4To7" in value ? ReportingDelay.Days4To7 : "Days8To15" in value ? ReportingDelay.Days8To15 : "Over15Days" in value ? ReportingDelay.Over15Days : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Available: null;
} | {
    NotAvailable: null;
} | {
    Pending: null;
}): BrigadeReport {
    return "Available" in value ? BrigadeReport.Available : "NotAvailable" in value ? BrigadeReport.NotAvailable : "Pending" in value ? BrigadeReport.Pending : value;
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Assessment>): Array<Assessment> {
    return value.map((x)=>from_candid_Assessment_n4(_uploadFile, _downloadFile, x));
}
function to_candid_AssessmentInput_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AssessmentInput): _AssessmentInput {
    return to_candid_record_n24(_uploadFile, _downloadFile, value);
}
function to_candid_BrigadeReport_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BrigadeReport): _BrigadeReport {
    return to_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function to_candid_DocumentStatus_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DocumentStatus): _DocumentStatus {
    return to_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function to_candid_FireCause_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FireCause): _FireCause {
    return to_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function to_candid_PolicyStatus_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PolicyStatus): _PolicyStatus {
    return to_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function to_candid_ReportingDelay_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReportingDelay): _ReportingDelay {
    return to_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function to_candid_SurveyorStatus_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SurveyorStatus): _SurveyorStatus {
    return to_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    brigadeReport: BrigadeReport;
    surveyorStatus: SurveyorStatus;
    fireCause: FireCause;
    fireCauseText: string;
    policyStatus: PolicyStatus;
    documentStatus: DocumentStatus;
    reportingDelayText: string;
    policyStatusText: string;
    additionalContext: string;
    brigadeReportText: string;
    documentStatusText: string;
    surveyorStatusText: string;
    reportingDelay: ReportingDelay;
}): {
    brigadeReport: _BrigadeReport;
    surveyorStatus: _SurveyorStatus;
    fireCause: _FireCause;
    fireCauseText: string;
    policyStatus: _PolicyStatus;
    documentStatus: _DocumentStatus;
    reportingDelayText: string;
    policyStatusText: string;
    additionalContext: string;
    brigadeReportText: string;
    documentStatusText: string;
    surveyorStatusText: string;
    reportingDelay: _ReportingDelay;
} {
    return {
        brigadeReport: to_candid_BrigadeReport_n25(_uploadFile, _downloadFile, value.brigadeReport),
        surveyorStatus: to_candid_SurveyorStatus_n27(_uploadFile, _downloadFile, value.surveyorStatus),
        fireCause: to_candid_FireCause_n29(_uploadFile, _downloadFile, value.fireCause),
        fireCauseText: value.fireCauseText,
        policyStatus: to_candid_PolicyStatus_n31(_uploadFile, _downloadFile, value.policyStatus),
        documentStatus: to_candid_DocumentStatus_n33(_uploadFile, _downloadFile, value.documentStatus),
        reportingDelayText: value.reportingDelayText,
        policyStatusText: value.policyStatusText,
        additionalContext: value.additionalContext,
        brigadeReportText: value.brigadeReportText,
        documentStatusText: value.documentStatusText,
        surveyorStatusText: value.surveyorStatusText,
        reportingDelay: to_candid_ReportingDelay_n35(_uploadFile, _downloadFile, value.reportingDelay)
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BrigadeReport): {
    Available: null;
} | {
    NotAvailable: null;
} | {
    Pending: null;
} {
    return value == BrigadeReport.Available ? {
        Available: null
    } : value == BrigadeReport.NotAvailable ? {
        NotAvailable: null
    } : value == BrigadeReport.Pending ? {
        Pending: null
    } : value;
}
function to_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SurveyorStatus): {
    Favourable: null;
} | {
    Unfavourable: null;
} | {
    NotAppointed: null;
} | {
    Pending: null;
} {
    return value == SurveyorStatus.Favourable ? {
        Favourable: null
    } : value == SurveyorStatus.Unfavourable ? {
        Unfavourable: null
    } : value == SurveyorStatus.NotAppointed ? {
        NotAppointed: null
    } : value == SurveyorStatus.Pending ? {
        Pending: null
    } : value;
}
function to_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FireCause): {
    NaturalCalamity: null;
} | {
    GasExplosion: null;
} | {
    Arson: null;
} | {
    Electrical: null;
} | {
    Other: null;
} | {
    Accidental: null;
} {
    return value == FireCause.NaturalCalamity ? {
        NaturalCalamity: null
    } : value == FireCause.GasExplosion ? {
        GasExplosion: null
    } : value == FireCause.Arson ? {
        Arson: null
    } : value == FireCause.Electrical ? {
        Electrical: null
    } : value == FireCause.Other ? {
        Other: null
    } : value == FireCause.Accidental ? {
        Accidental: null
    } : value;
}
function to_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PolicyStatus): {
    Inactive: null;
} | {
    Active: null;
} | {
    Unsure: null;
} {
    return value == PolicyStatus.Inactive ? {
        Inactive: null
    } : value == PolicyStatus.Active ? {
        Active: null
    } : value == PolicyStatus.Unsure ? {
        Unsure: null
    } : value;
}
function to_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DocumentStatus): {
    Complete: null;
} | {
    Partial: null;
} | {
    Incomplete: null;
} {
    return value == DocumentStatus.Complete ? {
        Complete: null
    } : value == DocumentStatus.Partial ? {
        Partial_: null
    } : value == DocumentStatus.Incomplete ? {
        Incomplete: null
    } : value;
}
function to_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReportingDelay): {
    Within3Days: null;
} | {
    SameDay: null;
} | {
    Days4To7: null;
} | {
    Days8To15: null;
} | {
    Over15Days: null;
} {
    return value == ReportingDelay.Within3Days ? {
        Within3Days: null
    } : value == ReportingDelay.SameDay ? {
        SameDay: null
    } : value == ReportingDelay.Days4To7 ? {
        Days4To7: null
    } : value == ReportingDelay.Days8To15 ? {
        Days8To15: null
    } : value == ReportingDelay.Over15Days ? {
        Over15Days: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
